### ISSUE TITLE
Секция со слайдером

### ISSUE THREAD

**Issue by igosheva** [kuzzzmenko/burgers#12]
http://joxi.ru/krD0EM7i0g1GWr - весь контент этой страницы должен лежать в контейнере, который имеет максимальную ширину и быть отцентрован по горизонтале.

**Comment by igosheva** [comment]
Стрелки arrow__scroll-left и arrow__scroll_right желательно объединить в единый блок. И соответственно относительно этого блока спозиционировать из абсолютно

**Comment by igosheva** [comment]
burgers__img-pic - тут свойство не min-width: 100%;, а max-width: 100%;. Оно нужно чтобы как раз таки картинка не вылазила за пределы своего родителя

**Comment by igosheva** [comment]
burgers__list - в мобильной версии расширить в целом контент и сделать элементы больше, сейчас слишком маленькие.

**Comment by kuzzzmenko** [comment]
Исправлено
