### ISSUE TITLE
Секция формы

### ISSUE THREAD

**Issue by igosheva** [kuzzzmenko/burgers#16]
order - добавить type='submit'
btn-clear - добавить type='reset'

**Comment by igosheva** [comment]
form-right - нужно уйти от фиксированных значений ширины. Можно заменить сочетанием ma-width в rem и width  в %. Все фиксированных значения ломают верстку, вот на примере твоей - http://joxi.ru/ZrJ05MEi1bJlP2 . Если бы просто поставил 100% такого бы не было

**Comment by kuzzzmenko** [comment]
Исправлено
