### ISSUE TITLE
Контент в первой секции

### ISSUE THREAD

**Issue by igosheva** [kuzzzmenko/burgers#6]
нужно выровнять весь контент таким образом, чтобы при любом расширении экрана шапка была всегда наверху, стрелка прокрутки ко второй секции всегда внизу, а основной контент всегда по центру. Должно быть так http://joxi.ru/zANjLWQHljObLA, а сейчас вот так http://joxi.ru/v29n1p7tGpqE5A

**Comment by kuzzzmenko** [comment]
Исправлено
